on:
  push:
    branches:
      - main
name: ðŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest
    # steps:
    #   - name: ðŸšš Get latest code
    #     uses: actions/checkout@v4
      # - name: Make envfile
      #   uses: SpicyPizza/create-envfile@v1
      #   with:
      #     envkey_DEBUG: false
      #     envkey_FOO: "foo"
      #     envkey_SECRET: ${{ secrets.SECRET }}
      #     # directory: <directory_name> # tmp disable for checking
      #     file_name: .env
      #     fail_on_empty: true
      # - name: Confirm env file
      #   run: cat .env
      # - uses: pnpm/action-setup@v4
      #   name: Install pnpm
      #   with:
      #     version: 10.8.0
      #     cache: false
      # - name: Install
      #   run: |
      #     pnpm install --frozen-lockfile
      # - name: Build
      #   run: |
      #     pnpm build
      # - name: ðŸ“‚ Sync files
      #   uses: SamKirkland/FTP-Deploy-Action@v4.3.6
      #   with:
      #     server: ${{ secrets.FTP_SERVER }}
      #     port: ${{ secrets.FTP_SERVER_PORT }}
      #     username: ${{ secrets.FTP_USRNAME }}
      #     password: ${{ secrets.FTP_PASSWORD }}
      #     local-dir: ./test/
      #     server-dir: ./domains/cdtphuhoi.com/public_html/
